sudo: required

before_install:
- openssl aes-256-cbc -K $encrypted_0d8df11c4167_key -iv $encrypted_0d8df11c4167_iv
  -in ./deploy_key -out id_rsa_travis_it -d
  
install:

- eval "$(ssh-agent -s)"
- chmod 600 ./id_rsa_travis_it
- echo -e "Host $HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./id_rsa_travis_it
- ssh -i ./id_rsa_travis_it $USER_TEST@$HOST -p $PORT 'bash $DEPLOY_PATH_TEST'

notifications:
  email:
    on_success: never
    on_failure: always
